/*
* This file was generated by a tool.
* Rerun `npm run db-gen` to regenerate this file.
*/
declare namespace DB {
  export interface migrations {
    id: number;
    name: string | null;
    batch: number | null;
    migration_time: Date | null;
  }
  
  export interface migrations_lock {
    index: number;
    is_locked: number | null;
  }
  
  export interface users {
    id: string;
    name: string;
    email: string;
    password: string;
  }
  
}

